# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//bazel/config/build_variant:compatibility.bzl", "unit_test_only")

label_flag(
    name = "transport_configuration",
    build_setting_default = "//executables/referenceApp/transportConfiguration:transport_configuration",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "transport_router_simple",
    srcs = [
        "src/transport/TpRouterLogger.cpp",
        "src/transport/routing/TransportRouterSimple.cpp",
    ],
    hdrs = [
        "include/transport/TpRouterLogger.h",
        "include/transport/routing/TransportRouterSimple.h",
    ],
    implementation_deps = [
        "//bazel/config/features:ethernet_defines",
        "//libs/bsw/common:configuration",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        ":transport_configuration",
        "//libs/bsw/transport",
    ],
)

cc_test(
    name = "transport_router_simple_test",
    srcs = ["test/src/TransportRouterSimpleTest.cpp"],
    target_compatible_with = unit_test_only(),
    deps = [
        ":transport_router_simple",
        "//executables/unitTest/transportConfiguration:transport_configuration",
        "//libs/3rdparty/etl",
        "//libs/3rdparty/googletest:gtest_main",
        "//libs/bsw/async:async_mock_impl",
        "//libs/bsw/transport:transport_mock",
        "//libs/bsw/util:util_mock",
    ],
)
