# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//bazel/config/build_variant:compatibility.bzl", "unit_test_only")

cc_test(
    name = "timer_test",
    srcs = ["src/TimerTest.cpp"],
    target_compatible_with = unit_test_only(),
    deps = [
        "//libs/3rdparty/googletest:gtest_main",
        "//libs/bsw/timer",
    ],
)
