# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "bsp_input_manager",
    srcs = [
        "src/inputManager/AlternativeDigitalInput.cpp",
        "src/inputManager/DigitalInput.cpp",
        "src/inputManager/DigitalInputTester.cpp",
    ],
    hdrs = [
        "include/inputManager/AlternativeDigitalInput.h",
        "include/inputManager/DigitalInput.h",
        "include/inputManager/DigitalInputTester.h",
    ],
    strip_include_prefix = "include",
    target_compatible_with = ["//bazel/platform/constraints/soc:s32k148"],
    visibility = ["//visibility:public"],
    deps = [
        "//bazel/config/bsp:bsp_configuration",
        "//libs/3rdparty/etl",
        "//libs/bsp/bspDynamicClient:bsp_dynamic_client",
        "//libs/bsp/bspInterrupts:bsp_interrupts",
        "//libs/bsw/bsp",
        "//libs/bsw/util",
        "//platforms/s32k1xx/bsp/bspIo:bsp_io",
    ],
)
