# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "transport",
    srcs = [
        "src/AbstractTransportLayer.cpp",
        "src/LogicalAddress.cpp",
        "src/TransportLogger.cpp",
        "src/TransportMessage.cpp",
    ],
    hdrs = [
        "include/transport/AbstractTransportLayer.h",
        "include/transport/BufferedTransportMessage.h",
        "include/transport/ITransportMessageListener.h",
        "include/transport/ITransportMessageProcessedListener.h",
        "include/transport/ITransportMessageProvider.h",
        "include/transport/ITransportMessageProvidingListener.h",
        "include/transport/LogicalAddress.h",
        "include/transport/TransportLogger.h",
        "include/transport/TransportMessage.h",
        "include/transport/TransportMessageSendJob.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/3rdparty/etl",
        "//libs/bsw/async",
        "//libs/bsw/common",
        "//libs/bsw/util",
    ],
)

cc_library(
    name = "transport_mock",
    testonly = True,
    srcs = [
        "mock/gmock/src/TransportMessageProvidingListenerMock.cpp",
    ],
    hdrs = [
        "mock/gmock/include/transport/AbstractTransportLayerMock.h",
        "mock/gmock/include/transport/TransportMessageListenerMock.h",
        "mock/gmock/include/transport/TransportMessageProcessedListenerMock.h",
        "mock/gmock/include/transport/TransportMessageProviderMock.h",
        "mock/gmock/include/transport/TransportMessageProvidingListenerMock.h",
    ],
    implementation_deps = [
        ":transport",
        "//libs/3rdparty/etl",
        "//libs/3rdparty/googletest:gtest",
    ],
    strip_include_prefix = "mock/gmock/include",
    visibility = ["//visibility:public"],
)
