# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("//bazel/config/build_variant:compatibility.bzl", "unit_test_only")

cc_library(
    name = "bsp",
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/3rdparty/etl",
        "//libs/bsw/common:common_headers",
    ],
)

cc_library(
    name = "bsp_mock",
    srcs = [
        "mock/src/bsp/timer/SystemTimerMock.cpp",
    ],
    hdrs = [
        "mock/include/bsp/Uart.h",
        "mock/include/bsp/can/canTransceiver/CanPhyMock.h",
        "mock/include/bsp/eeprom/EepromDriverMock.h",
        "mock/include/bsp/eepromemulation/EepromEmulationDriverMock.h",
        "mock/include/bsp/flash/FlashDriverMock.h",
        "mock/include/bsp/flash/FlashMock.h",
        "mock/include/bsp/power/EcuPowerStateControllerMock.h",
        "mock/include/bsp/timer/SystemTimerMock.h",
        "mock/include/inputManager/DigitalInput.h",
        "mock/include/outputManager/Output.h",
    ],
    strip_include_prefix = "mock/include",
    target_compatible_with = unit_test_only(),
    visibility = ["//visibility:public"],
    deps = [
        ":bsp",
        "//libs/3rdparty/etl",
        "//libs/3rdparty/googletest:gtest_main",
    ],
)
