# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

# Circular dependency present on the CMake side: uds -> udsConfiguration -> uds
# Split off uds_headers to break the circular dependency for Bazel
cc_library(
    name = "uds_headers",
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/3rdparty/etl",
        "//libs/bsw/async:async_headers",
        "//libs/bsw/transport",
        "//libs/bsw/util",
    ],
)

cc_library(
    name = "uds",
    srcs = glob(["src/**/*.cpp"]),
    visibility = ["//visibility:public"],
    deps = [
        ":uds_headers",
        "//executables/referenceApp/transportConfiguration:transport_configuration",
        "//executables/referenceApp/udsConfiguration:uds_configuration",
        "//libs/bsw/async",
        "//libs/bsw/bsp",
        "//libs/bsw/common:configuration",
    ],
)

cc_library(
    name = "uds_with_mock",
    testonly = True,
    visibility = ["//visibility:public"],
    deps = [
        ":uds",
        ":uds_mock",
    ],
)

cc_library(
    name = "uds_mock",
    testonly = True,
    srcs = ["mock/gmock/src/uds/session/DiagSessionMock.cpp"],
    hdrs = glob(["mock/gmock/include/**/*.h"]),
    implementation_deps = [
        ":uds_headers",
    ],
    strip_include_prefix = "mock/gmock/include",
    visibility = ["//visibility:public"],
    deps = [
        "//executables/referenceApp/udsConfiguration:uds_configuration",
        "//libs/3rdparty/googletest:gtest",
    ],
)
