# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "util",
    srcs = glob(["src/util/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/3rdparty/etl",
    ],
)

cc_library(
    name = "util_mock",
    testonly = True,
    srcs = [
        "mock/gmock/src/util/StdIoMock.cpp",
        "mock/gmock/src/util/logger/TestConsoleLogger.cpp",
    ],
    hdrs = [
        "mock/gmock/include/util/StdIoMock.h",
        "mock/gmock/include/util/estd/function_mock.h",
        "mock/gmock/include/util/estd/gtest_extensions.h",
        "mock/gmock/include/util/logger/ComponentMappingMock.h",
        "mock/gmock/include/util/logger/LoggerOutputMock.h",
        "mock/gmock/include/util/logger/TestConsoleLogger.h",
        "mock/gmock/include/util/stream/OutputStreamMock.h",
        "mock/gmock/include/util/stream/SharedOutputStreamMock.h",
    ],
    strip_include_prefix = "mock/gmock/include",
    visibility = ["//visibility:public"],
    deps = [
        ":util",
        "//libs/3rdparty/etl",
        "//libs/3rdparty/googletest:gtest",
    ],
)
