# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "cpp2ethernet",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/3rdparty/etl",
        "//libs/bsw/async",
        "//libs/bsw/bsp",
        "//libs/bsw/common",
        "//libs/bsw/shed",
        "//libs/bsw/util",
    ],
)

cc_library(
    name = "cpp2ethernet_mock",
    testonly = True,
    hdrs = glob(["mock/include/**/*.h"]),
    strip_include_prefix = "mock/include",
    visibility = ["//visibility:public"],
    deps = [
        ":cpp2ethernet",
    ],
)
