# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "bsp_output_manager",
    srcs = [
        "src/outputManager/Output.cpp",
        "src/outputManager/OutputTester.cpp",
    ],
    hdrs = [
        "include/outputManager/Output.h",
        "include/outputManager/OutputTester.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        ":bsp_io",
        "//bazel/config/bsp:bsp_configuration",
        "//libs/3rdparty/etl",
        "//libs/bsp/bspDynamicClient:bsp_dynamic_client",
        "//libs/bsp/bspInterrupts:bsp_interrupts",
        "//libs/bsw/util",
    ],
)

# bspIo implementation. Every platform must declare this via its platform flags.
# Posix has no bspIo as bsp_output_manager is not linked in posix executables.
#   Override: --//libs/bsp/bspOutputManager:bsp_io=//path/to:your_bsp_io
label_flag(
    name = "bsp_io",
    build_setting_default = "//bazel/config:no_implementation",
    visibility = ["//visibility:public"],
)
