# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//bazel/config/build_variant:compatibility.bzl", "unit_test_only")

cc_library(
    name = "safe_monitor",
    hdrs = [
        "include/safeMonitor/Register.h",
        "include/safeMonitor/Sequence.h",
        "include/safeMonitor/Trigger.h",
        "include/safeMonitor/Value.h",
        "include/safeMonitor/Watchdog.h",
        "include/safeMonitor/common.h",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/bsw/common",
    ],
)

cc_test(
    name = "safe_monitor_test",
    srcs = [
        "test/include/common.h",
        "test/src/RegisterTest.cpp",
        "test/src/SequenceTest.cpp",
        "test/src/TriggerTest.cpp",
        "test/src/ValueTest.cpp",
        "test/src/WatchdogTest.cpp",
        "test/src/common.cpp",
    ],
    includes = ["test/include"],
    target_compatible_with = unit_test_only(),
    deps = [
        ":safe_monitor",
        "//libs/3rdparty/googletest:gtest_main",
    ],
)
