# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

cc_library(
    name = "cpp2can",
    srcs = [
        "src/can/CanLogger.cpp",
        "src/can/canframes/CANFrame.cpp",
        "src/can/filter/AbstractStaticBitFieldFilter.cpp",
        "src/can/filter/BitFieldFilter.cpp",
        "src/can/filter/IntervalFilter.cpp",
        "src/can/filter/MaskFilter.cpp",
        "src/can/transceiver/AbstractCANTransceiver.cpp",
    ],
    hdrs = glob(["include/**/*.h"]),
    implementation_deps = [
        "//libs/bsp/bspInterrupts:bsp_interrupts",
        "//libs/bsw/bsp",
    ],
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/3rdparty/etl",
        "//libs/bsw/common",
        "//libs/bsw/util",
    ],
)

cc_library(
    name = "cpp2can_mock",
    testonly = True,
    srcs = [
        "mock/src/can/transceiver/AbstractCANTransceiverMock.cpp",
    ],
    hdrs = [
        "mock/include/can/canframes/CANFrameSentListenerMock.h",
        "mock/include/can/filter/FilterMock.h",
        "mock/include/can/filter/MergerMock.h",
        "mock/include/can/framemgmt/CANFrameListenerMock.h",
        "mock/include/can/framemgmt/FilteredCANFrameSentListenerMock.h",
        "mock/include/can/transceiver/AbstractCANTransceiverMock.h",
        "mock/include/can/transceiver/ICanTransceiverMock.h",
    ],
    implementation_deps = [
        ":cpp2can",
        "//libs/3rdparty/googletest:gtest_main",
        "//libs/bsw/bsp:bsp_mock",
    ],
    strip_include_prefix = "mock/include",
    visibility = ["//visibility:public"],
)
