# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load(
    "//libs/bsw/middleware/tools/cpp_generator:middleware_codegen.bzl",
    "middleware_codegen",
)
load(":generated_outputs.bzl", "GENERATED_OUTPUTS")

middleware_codegen(
    name = "middleware_configuration_generated",
    deployment_yaml = "model/deployment.yaml",
    generated_outputs = GENERATED_OUTPUTS,
    visibility = ["//visibility:public"],
    deps = ["//libs/bsw/middleware"],
)

cc_library(
    name = "middleware_configuration",
    srcs = [
        "platform_integration/logger/src/LoggerImpl.cpp",
        "platform_integration/os/src/OsDefinitions.cpp",
        "platform_integration/time/src/SystemTimeProvider.cpp",
        "src/MemoryLayout.cpp",
    ],
    hdrs = ["include/MemoryLayout.h"],
    implementation_deps = [
        "//executables/referenceApp/application:demo_logger",
        "//libs/bsw/bsp",
    ],
    strip_include_prefix = "include",
    target_compatible_with = ["@platforms//os:linux"],
    visibility = ["//visibility:public"],
    deps = [
        ":middleware_configuration_generated",
        "//executables/referenceApp/asyncBinding:async_binding",
        "//libs/bsw/logger",
        "//libs/bsw/middleware",
    ],
    # NOTE: alwayslink is required because LoggerImpl.cpp implements
    # middleware::logger::logBinary(), a symbol declared inside //libs/bsw/middleware.
    alwayslink = True,
)
