# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")

label_flag(
    name = "routing_configuration",
    build_setting_default = "//executables/referenceApp/configuration:routing_configuration_headers",
    visibility = ["//visibility:public"],
)

cc_library(
    name = "routing",
    srcs = glob(["src/routing/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        ":routing_configuration",
        "//libs/3rdparty/etl",
        "//libs/bsw/blob",
        "//libs/bsw/bsp",
        "//libs/bsw/cpp2ethernet",
        "//libs/bsw/io",
        "//libs/bsw/lwipSocket:lwip_socket",
        "//libs/bsw/util",
    ],
)
