# *******************************************************************************
# Copyright (c) 2026 Accenture
#
# This program and the accompanying materials are made available under the
# terms of the Apache License Version 2.0 which is available at
# https://www.apache.org/licenses/LICENSE-2.0
#
# SPDX-License-Identifier: Apache-2.0
# *******************************************************************************

load("@rules_cc//cc:cc_library.bzl", "cc_library")
load("@rules_cc//cc:cc_test.bzl", "cc_test")
load("//bazel/config/build_variant:compatibility.bzl", "unit_test_only")

cc_library(
    name = "doip",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.h"]),
    strip_include_prefix = "include",
    visibility = ["//visibility:public"],
    deps = [
        "//libs/3rdparty/etl",
        "//libs/bsw/async",
        "//libs/bsw/common",
        "//libs/bsw/cpp2ethernet",
        "//libs/bsw/transport",
        "//libs/bsw/util",
    ],
)

cc_library(
    name = "doip_mock",
    hdrs = glob(["mock/gmock/include/**/*.h"]),
    strip_include_prefix = "mock/gmock/include",
    target_compatible_with = unit_test_only(),
    visibility = ["//visibility:public"],
    deps = [
        ":doip",
        "//libs/3rdparty/googletest:gtest",
    ],
)

cc_test(
    name = "doip_test",
    srcs = glob(["test/src/**/*.cpp"]) + [
        "test/include/doip/common/DoIpTestHelpers.h",
    ],
    includes = ["test/include"],
    target_compatible_with = unit_test_only(),
    deps = [
        ":doip",
        ":doip_mock",
        "//libs/3rdparty/googletest:gtest_esr_extensions",
        "//libs/3rdparty/googletest:gtest_main",
        "//libs/bsw/async:async_mock_impl",
        "//libs/bsw/bsp:bsp_mock",
        "//libs/bsw/cpp2ethernet",
        "//libs/bsw/cpp2ethernet:cpp2ethernet_mock",
        "//libs/bsw/transport:transport_mock",
        "//libs/bsw/util",
        "//libs/bsw/util:util_mock",
    ],
)
